ALTER SESSION SET NLS_DATE_FORMAT = 'HH24:MI:SS DD/MM/YYYY';
CREATE ROLE ROLE_MANAGER;
GRANT ROLE_MANAGER TO DEV;
CREATE USER QUANLY IDENTIFIED BY 1;
REVOKE 
GRANT ROLE_MAN TO QUANLY;

SELECT * FROM SESSION_ROLES;
SELECT * FROM SESSION_ROLES WHERE ROLE ='ROLE_USER';
SELECT * FROM ALL_USERS WHERE CREATED >= TO_DATE('18:22:48 22/11/2023', 'HH24:MI:SS DD/MM/YYYY');


// DAC
GRANT CREATE SESSION, CONNECT TO ROLE_MANAGER;
GRANT SELECT ON DEV.ROOM  TO ROLE_MANAGER;
GRANT SELECT ON DEV.BOOKING TO ROLE_MANAGER;
GRANT SELECT ON DEV.RECEIPT TO ROLE_MANAGER;
GRANT SELECT ON DEV.USER_INFOR TO ROLE_MANAGER;

// ROOM
GRANT EXECUTE ON DEV.INSERT_ROOM TO ROLE_MANAGER;
GRANT EXECUTE ON DEV.UPDATE_ROOM TO ROLE_MANAGER;
GRANT EXECUTE ON DEV.DELETE_ROOM TO ROLE_MANAGER;
// USER
GRANT EXECUTE ON DEV.UPDATE_USER TO ROLE_MANAGER;
--GRANT EXECUTE ON DEV.BOOKING_PKG.INSERT_BOOKING TO ROLE_USER;

SELECT * FROM DEV.ROOM;
SELECT * FROM DEV.BOOKING;
SELECT * FROM DEV.RECEIPT;
SELECT * FROM DEV.USER_INFOR;

