ALTER SESSION SET NLS_DATE_FORMAT = 'HH24:MI:SS DD/MM/YYYY';
CREATE ROLE ROLE_USER;
CREATE USER TESTER IDENTIFIED BY 1;
GRANT ROLE_USER TO TESTER;

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTED_ROLE LIKE '%' || 'ROLE_' || '%';
SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE LIKE '%' || 'ROLE_' || '%';
SELECT * FROM ROLE_TAB_PRIVS WHERE

SELECT * FROM SESSION_ROLES 
WHERE ROLE = 'ROLE_USER';
SELECT * FROM USER_ROLE_PRIVS;
SELECT * FROM ALL_USERS WHERE CREATED >= TO_DATE('18:22:48 22/11/2023', 'HH24:MI:SS DD/MM/YYYY');

// DAC
GRANT CREATE SESSION, CONNECT TO ROLE_USER;
GRANT SELECT ON DEV.ROOM  TO ROLE_USER;
GRANT SELECT ON DEV.BOOKING TO ROLE_USER;
GRANT SELECT ON DEV.RECEIPT TO ROLE_USER;
GRANT SELECT ON DEV.USER_INFOR TO ROLE_USER;

GRANT EXECUTE ON DEV.UPDATE_ROOM TO ROLE_USER;
GRANT EXECUTE ON DEV.INSERT_BOOKING TO ROLE_USER;
GRANT EXECUTE ON DEV.UPDATE_BOOKING TO ROLE_USER;
GRANT EXECUTE ON DEV.INSERT_RECEIPT TO ROLE_USER;
GRANT EXECUTE ON DEV.UPDATE_USER TO ROLE_USER;


--GRANT EXECUTE ON DEV.BOOKING_PKG.INSERT_BOOKING TO ROLE_USER;

SELECT * FROM DEV.ROOM;
SELECT * FROM DEV.BOOKING;
SELECT * FROM DEV.RECEIPT;
SELECT * FROM DEV.USER_INFOR;
