/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.DB;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author vogiadat
 */
public class Authencation extends javax.swing.JFrame {

	/**
	 * Creates new form Authencation
	 */
	public Authencation() {
		initComponents();
	}

	public static void moveButtonAnimation(Component component, int targetX,
	int targetY) {
		int duration = 100;
		int steps = 100; // Number of animation steps
		int initialX = component.getX();
		int initialY = component.getY();
		int deltaX = (targetX - initialX) / steps;
		int deltaY = (targetY - initialY) / steps;

		Timer timer = new Timer(duration / steps, new ActionListener() {
			int step = 0;

			@Override
			public void actionPerformed(ActionEvent e) {
				if (step < steps) {
					component.setLocation(component.getX() + deltaX, component.getY() + deltaY);
					step++;
				} else {
					((Timer) e.getSource()).stop(); // Animation completed, stop the timer
				}
			}
		});

		timer.start();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panel_authencation = new javax.swing.JLayeredPane();
                panel_login = new javax.swing.JLayeredPane();
                login_lbLogin = new javax.swing.JLabel();
                login_txtUsername = new javax.swing.JTextField();
                login_lbUsername = new javax.swing.JLabel();
                login_sepUsername = new javax.swing.JSeparator();
                login_lbPassword = new javax.swing.JLabel();
                login_sepUsername1 = new javax.swing.JSeparator();
                login_txtPassword = new javax.swing.JPasswordField();
                login_btnLogin = new javax.swing.JButton();
                login_lbNotUser = new javax.swing.JLabel();
                login_lbRegister = new javax.swing.JLabel();
                panel_register = new javax.swing.JLayeredPane();
                lb_register = new javax.swing.JLabel();
                register_lbUsername = new javax.swing.JLabel();
                register_txtUsername = new javax.swing.JTextField();
                register_lbPassword = new javax.swing.JLabel();
                register_sepPassword = new javax.swing.JSeparator();
                register_sepUsername = new javax.swing.JSeparator();
                register_btnRegister = new javax.swing.JButton();
                register_txtPassword = new javax.swing.JPasswordField();
                register_lbLogin = new javax.swing.JLabel();
                register_lbIsUser = new javax.swing.JLabel();
                panel_layout = new javax.swing.JLayeredPane();
                btn_close = new javax.swing.JButton();
                panel_image = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);
                setResizable(false);

                panel_authencation.setBackground(new java.awt.Color(25, 118, 211));
                panel_authencation.setInheritsPopupMenu(true);
                panel_authencation.setPreferredSize(new java.awt.Dimension(800, 600));

                panel_login.setOpaque(true);
                panel_login.setPreferredSize(new java.awt.Dimension(400, 600));

                login_lbLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
                login_lbLogin.setForeground(new java.awt.Color(255, 255, 255));
                login_lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                login_lbLogin.setText("Login");

                login_txtUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                login_txtUsername.setForeground(new java.awt.Color(25, 118, 211));
                login_txtUsername.setBorder(null);
                login_txtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
                login_txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                login_txtUsername.setFocusTraversalPolicyProvider(true);
                login_txtUsername.setPreferredSize(new java.awt.Dimension(64, 20));
                login_txtUsername.setSelectedTextColor(new java.awt.Color(204, 255, 255));

                login_lbUsername.setBackground(new java.awt.Color(255, 255, 255));
                login_lbUsername.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
                login_lbUsername.setForeground(new java.awt.Color(255, 255, 255));
                login_lbUsername.setText("Username");

                login_sepUsername.setForeground(new java.awt.Color(255, 255, 255));

                login_lbPassword.setBackground(new java.awt.Color(255, 255, 255));
                login_lbPassword.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
                login_lbPassword.setForeground(new java.awt.Color(255, 255, 255));
                login_lbPassword.setText("Password");

                login_sepUsername1.setForeground(new java.awt.Color(255, 255, 255));

                login_txtPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                login_txtPassword.setForeground(new java.awt.Color(25, 118, 211));
                login_txtPassword.setBorder(null);
                login_txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                login_txtPassword.setFocusTraversalPolicyProvider(true);
                login_txtPassword.setSelectedTextColor(new java.awt.Color(204, 255, 255));

                login_btnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
                login_btnLogin.setForeground(new java.awt.Color(25, 118, 211));
                login_btnLogin.setText("LOGIN");
                login_btnLogin.setBorder(null);
                login_btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                login_btnLogin.setIconTextGap(6);
                login_btnLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                login_btnLoginActionPerformed(evt);
                        }
                });

                login_lbNotUser.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
                login_lbNotUser.setForeground(new java.awt.Color(255, 255, 255));
                login_lbNotUser.setText("Don't have an account?");

                login_lbRegister.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
                login_lbRegister.setForeground(new java.awt.Color(255, 255, 255));
                login_lbRegister.setText("Register");
                login_lbRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                login_lbRegister.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                login_lbRegisterMouseClicked(evt);
                        }
                });

                panel_login.setLayer(login_lbLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_txtUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_lbUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_sepUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_lbPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_sepUsername1, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_btnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_lbNotUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_login.setLayer(login_lbRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
                panel_login.setLayout(panel_loginLayout);
                panel_loginLayout.setHorizontalGroup(
                        panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_loginLayout.createSequentialGroup()
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_loginLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(login_lbLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panel_loginLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(login_lbPassword)
                                                        .addComponent(login_lbUsername)
                                                        .addComponent(login_sepUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(login_sepUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panel_loginLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(login_txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(login_txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 22, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(login_btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_loginLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(login_lbNotUser)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(login_lbRegister)))
                                .addGap(22, 22, 22))
                );
                panel_loginLayout.setVerticalGroup(
                        panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_loginLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(login_lbLogin)
                                .addGap(18, 18, 18)
                                .addComponent(login_lbUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(login_txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(login_sepUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(login_lbPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(login_txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(login_sepUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(login_btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(login_lbNotUser)
                                        .addComponent(login_lbRegister))
                                .addContainerGap(104, Short.MAX_VALUE))
                );

                panel_register.setOpaque(true);
                panel_register.setPreferredSize(new java.awt.Dimension(400, 600));

                lb_register.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
                lb_register.setForeground(new java.awt.Color(255, 255, 255));
                lb_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lb_register.setText("Register");

                register_lbUsername.setBackground(new java.awt.Color(255, 255, 255));
                register_lbUsername.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
                register_lbUsername.setForeground(new java.awt.Color(255, 255, 255));
                register_lbUsername.setText("Username");

                register_txtUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                register_txtUsername.setForeground(new java.awt.Color(25, 118, 211));
                register_txtUsername.setBorder(null);
                register_txtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
                register_txtUsername.setPreferredSize(new java.awt.Dimension(64, 20));

                register_lbPassword.setBackground(new java.awt.Color(255, 255, 255));
                register_lbPassword.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
                register_lbPassword.setForeground(new java.awt.Color(255, 255, 255));
                register_lbPassword.setText("Password");

                register_sepPassword.setForeground(new java.awt.Color(255, 255, 255));

                register_sepUsername.setForeground(new java.awt.Color(255, 255, 255));

                register_btnRegister.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
                register_btnRegister.setForeground(new java.awt.Color(25, 118, 211));
                register_btnRegister.setText("REGISTER");
                register_btnRegister.setBorder(null);
                register_btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                register_btnRegister.setIconTextGap(6);
                register_btnRegister.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                register_btnRegisterActionPerformed(evt);
                        }
                });

                register_txtPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                register_txtPassword.setForeground(new java.awt.Color(25, 118, 211));
                register_txtPassword.setBorder(null);

                register_lbLogin.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
                register_lbLogin.setForeground(new java.awt.Color(255, 255, 255));
                register_lbLogin.setText("Login");
                register_lbLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                register_lbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                register_lbLoginMouseClicked(evt);
                        }
                });

                register_lbIsUser.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
                register_lbIsUser.setForeground(new java.awt.Color(255, 255, 255));
                register_lbIsUser.setText("You're user");

                panel_register.setLayer(lb_register, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_lbUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_txtUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_lbPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_sepPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_sepUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_btnRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_register.setLayer(register_lbLogin, javax.swing.JLayeredPane.DRAG_LAYER);
                panel_register.setLayer(register_lbIsUser, javax.swing.JLayeredPane.DRAG_LAYER);

                javax.swing.GroupLayout panel_registerLayout = new javax.swing.GroupLayout(panel_register);
                panel_register.setLayout(panel_registerLayout);
                panel_registerLayout.setHorizontalGroup(
                        panel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_registerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_registerLayout.createSequentialGroup()
                                                .addGroup(panel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(register_btnRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(panel_registerLayout.createSequentialGroup()
                                                                .addComponent(register_lbIsUser)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(register_lbLogin)))
                                                .addGap(22, 22, 22))
                                        .addGroup(panel_registerLayout.createSequentialGroup()
                                                .addGroup(panel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(register_lbUsername)
                                                        .addComponent(register_lbPassword)
                                                        .addComponent(register_sepPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(register_sepUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panel_registerLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(panel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(register_txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(register_txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(28, Short.MAX_VALUE))))
                );
                panel_registerLayout.setVerticalGroup(
                        panel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_registerLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(lb_register)
                                .addGap(18, 18, 18)
                                .addComponent(register_lbUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(register_txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(register_sepUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(register_lbPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(register_txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(register_sepPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(register_btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(register_lbIsUser)
                                        .addComponent(register_lbLogin))
                                .addContainerGap())
                );

                panel_layout.setBackground(new java.awt.Color(255, 255, 255));
                panel_layout.setEnabled(false);
                panel_layout.setFocusable(false);
                panel_layout.setOpaque(true);
                panel_layout.setPreferredSize(new java.awt.Dimension(400, 600));

                btn_close.setBackground(new java.awt.Color(255, 0, 0));
                btn_close.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
                btn_close.setForeground(new java.awt.Color(255, 255, 255));
                btn_close.setText("X");
                btn_close.setAlignmentY(0.0F);
                btn_close.setMargin(new java.awt.Insets(0, 0, 0, 0));
                btn_close.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_closeActionPerformed(evt);
                        }
                });

                panel_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authencation.png"))); // NOI18N
                panel_image.setText("jLabel1");
                panel_image.setPreferredSize(new java.awt.Dimension(400, 600));

                panel_layout.setLayer(btn_close, javax.swing.JLayeredPane.DRAG_LAYER);
                panel_layout.setLayer(panel_image, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout panel_layoutLayout = new javax.swing.GroupLayout(panel_layout);
                panel_layout.setLayout(panel_layoutLayout);
                panel_layoutLayout.setHorizontalGroup(
                        panel_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_layoutLayout.createSequentialGroup()
                                .addContainerGap(374, Short.MAX_VALUE)
                                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                        .addGroup(panel_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_layoutLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(panel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
                panel_layoutLayout.setVerticalGroup(
                        panel_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_layoutLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(574, Short.MAX_VALUE))
                        .addGroup(panel_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_layoutLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(panel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );

                panel_authencation.setLayer(panel_login, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_authencation.setLayer(panel_register, javax.swing.JLayeredPane.DEFAULT_LAYER);
                panel_authencation.setLayer(panel_layout, javax.swing.JLayeredPane.DRAG_LAYER);

                javax.swing.GroupLayout panel_authencationLayout = new javax.swing.GroupLayout(panel_authencation);
                panel_authencation.setLayout(panel_authencationLayout);
                panel_authencationLayout.setHorizontalGroup(
                        panel_authencationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_authencationLayout.createSequentialGroup()
                                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(400, Short.MAX_VALUE))
                        .addGroup(panel_authencationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_authencationLayout.createSequentialGroup()
                                        .addGap(400, 400, 400)
                                        .addComponent(panel_layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)))
                        .addGroup(panel_authencationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_authencationLayout.createSequentialGroup()
                                        .addGap(400, 400, 400)
                                        .addComponent(panel_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
                panel_authencationLayout.setVerticalGroup(
                        panel_authencationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_authencationLayout.createSequentialGroup()
                                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(panel_authencationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_authencationLayout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addComponent(panel_layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)))
                        .addGroup(panel_authencationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_authencationLayout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addComponent(panel_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(panel_authencation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(panel_authencation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void login_lbRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_lbRegisterMouseClicked
		moveButtonAnimation(panel_layout, 0, 0);
		btn_close.setLocation(10, 10);
        }//GEN-LAST:event_login_lbRegisterMouseClicked

        private void register_lbLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_lbLoginMouseClicked
		moveButtonAnimation(panel_layout, 400, 0);
		btn_close.setLocation(370, 10);
        }//GEN-LAST:event_register_lbLoginMouseClicked

        private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
		this.dispose();
        }//GEN-LAST:event_btn_closeActionPerformed

        private void register_btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnRegisterActionPerformed
		DAL.User User = new DAL.User();
		String username = register_txtUsername.getText().toUpperCase();
		String password = String.valueOf(register_txtPassword.getPassword());

		if (User.createUser(username, password, username + "@test.vn")) {
			DB.user = username;
			DB.pass = password;
			Connection conn = DB.connect();
			try {
				if (conn != null) {
					JOptionPane.showMessageDialog(rootPane, "Register success!!!");
					this.dispose();
					new MainFrame().setVisible(rootPaneCheckingEnabled);
				} else {
					JOptionPane.showMessageDialog(null, "Invaild username/password!");
				}
			} catch (HeadlessException e) {
				JOptionPane.showMessageDialog(null, e);
			}
		}
        }//GEN-LAST:event_register_btnRegisterActionPerformed

        private void login_btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnLoginActionPerformed
		DB.user = login_txtUsername.getText();
		DB.pass = String.valueOf(login_txtPassword.getPassword());
		Connection conn = DB.connect();
		try {
			if (conn != null) {
				JOptionPane.showMessageDialog(rootPane, "Login success!!!");
				this.dispose();
				new MainFrame().setVisible(rootPaneCheckingEnabled);
			} else {
				JOptionPane.showMessageDialog(null, "Invaild username/password!");
			}
		} catch (HeadlessException e) {
			JOptionPane.showMessageDialog(null, e);
		}
        }//GEN-LAST:event_login_btnLoginActionPerformed

	/**
	 * @param args the command line arguments
	 */
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_close;
        private javax.swing.JLabel lb_register;
        private javax.swing.JButton login_btnLogin;
        private javax.swing.JLabel login_lbLogin;
        private javax.swing.JLabel login_lbNotUser;
        private javax.swing.JLabel login_lbPassword;
        private javax.swing.JLabel login_lbRegister;
        private javax.swing.JLabel login_lbUsername;
        private javax.swing.JSeparator login_sepUsername;
        private javax.swing.JSeparator login_sepUsername1;
        private javax.swing.JPasswordField login_txtPassword;
        private javax.swing.JTextField login_txtUsername;
        private javax.swing.JLayeredPane panel_authencation;
        private javax.swing.JLabel panel_image;
        private javax.swing.JLayeredPane panel_layout;
        private javax.swing.JLayeredPane panel_login;
        private javax.swing.JLayeredPane panel_register;
        private javax.swing.JButton register_btnRegister;
        private javax.swing.JLabel register_lbIsUser;
        private javax.swing.JLabel register_lbLogin;
        private javax.swing.JLabel register_lbPassword;
        private javax.swing.JLabel register_lbUsername;
        private javax.swing.JSeparator register_sepPassword;
        private javax.swing.JSeparator register_sepUsername;
        private javax.swing.JPasswordField register_txtPassword;
        private javax.swing.JTextField register_txtUsername;
        // End of variables declaration//GEN-END:variables
}
