/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.DB;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author vogiadat
 */
public class Connect extends javax.swing.JFrame {

	/**
	 * Creates new form Connect
	 */
	public Connect() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panel_connect = new javax.swing.JPanel();
                connect_lbTitle = new javax.swing.JLabel();
                connect_lbHost = new javax.swing.JLabel();
                connect_sep = new javax.swing.JSeparator();
                connect_txtHost = new javax.swing.JTextField();
                connect_lbPort = new javax.swing.JLabel();
                connect_txtPort = new javax.swing.JTextField();
                connect_lbSID = new javax.swing.JLabel();
                connect_txtSID = new javax.swing.JTextField();
                connect_btnConnect = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(255, 255, 255));

                panel_connect.setBackground(new java.awt.Color(204, 255, 255));

                connect_lbTitle.setBackground(new java.awt.Color(25, 118, 211));
                connect_lbTitle.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
                connect_lbTitle.setForeground(new java.awt.Color(25, 118, 211));
                connect_lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                connect_lbTitle.setText("CONNECT TO DATABASE");

                connect_lbHost.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                connect_lbHost.setForeground(new java.awt.Color(25, 118, 211));
                connect_lbHost.setText("HOST:");

                connect_sep.setBackground(new java.awt.Color(255, 255, 255));
                connect_sep.setForeground(new java.awt.Color(25, 118, 211));

                connect_txtHost.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                connect_txtHost.setForeground(new java.awt.Color(25, 118, 211));
                connect_txtHost.setText("localhost");
                connect_txtHost.setBorder(null);

                connect_lbPort.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                connect_lbPort.setForeground(new java.awt.Color(25, 118, 211));
                connect_lbPort.setText("PORT:");

                connect_txtPort.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                connect_txtPort.setForeground(new java.awt.Color(25, 118, 211));
                connect_txtPort.setText("1521");
                connect_txtPort.setBorder(null);

                connect_lbSID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                connect_lbSID.setForeground(new java.awt.Color(25, 118, 211));
                connect_lbSID.setText("SID:");

                connect_txtSID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                connect_txtSID.setForeground(new java.awt.Color(25, 118, 211));
                connect_txtSID.setText("ks");
                connect_txtSID.setBorder(null);

                connect_btnConnect.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                connect_btnConnect.setForeground(new java.awt.Color(25, 118, 211));
                connect_btnConnect.setText("Connect");
                connect_btnConnect.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                connect_btnConnectActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout panel_connectLayout = new javax.swing.GroupLayout(panel_connect);
                panel_connect.setLayout(panel_connectLayout);
                panel_connectLayout.setHorizontalGroup(
                        panel_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(connect_sep)
                        .addGroup(panel_connectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(connect_btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(connect_lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panel_connectLayout.createSequentialGroup()
                                                .addComponent(connect_lbHost)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(connect_txtHost))
                                        .addGroup(panel_connectLayout.createSequentialGroup()
                                                .addComponent(connect_lbPort)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(connect_txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(connect_lbSID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(connect_txtSID, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                panel_connectLayout.setVerticalGroup(
                        panel_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_connectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(connect_lbTitle)
                                .addGap(5, 5, 5)
                                .addComponent(connect_sep, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(connect_lbHost)
                                        .addComponent(connect_txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(connect_lbPort)
                                        .addComponent(connect_txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(connect_lbSID)
                                        .addComponent(connect_txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(connect_btnConnect)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel_connect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel_connect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void connect_btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_btnConnectActionPerformed
		String host, port, SID;
		host = (String) connect_txtHost.getText();
		port = (String) connect_txtPort.getText();
		SID = (String) connect_txtSID.getText();
		if (!host.isEmpty() && !port.isEmpty() && !SID.isEmpty()) {
			DB.server = "";
			DB.server += host + ":" + port + ":" + SID;
		}
		Connection conn = DB.getConnect();
		try {
			if (conn != null) {
				JOptionPane.showMessageDialog(rootPane, "Connecting Oracle...");
				this.dispose();
				new Authencation().setVisible(rootPaneCheckingEnabled);
			} else {
				JOptionPane.showMessageDialog(null, "Connect fail!!!");
			}
		} catch (HeadlessException e) {
			JOptionPane.showMessageDialog(null, e);
		}
        }//GEN-LAST:event_connect_btnConnectActionPerformed

	/**
	 * @param args the command line arguments
	 */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton connect_btnConnect;
        private javax.swing.JLabel connect_lbHost;
        private javax.swing.JLabel connect_lbPort;
        private javax.swing.JLabel connect_lbSID;
        private javax.swing.JLabel connect_lbTitle;
        private javax.swing.JSeparator connect_sep;
        private javax.swing.JTextField connect_txtHost;
        private javax.swing.JTextField connect_txtPort;
        private javax.swing.JTextField connect_txtSID;
        private javax.swing.JPanel panel_connect;
        // End of variables declaration//GEN-END:variables
}
